name: medconb
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - libffi=3.4.2
  - libsqlite=3.39.4
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=3.1.3
  - pip=23.1.2
  - python=3.10.6
  - readline=8.1.2
  - setuptools=65.4.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - pip:
    - annotated-types==0.5.0
    - anyio==3.6.1
    - ariadne==0.16.1
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - authlib==1.1.0
    - backcall==0.2.0
    - black==22.10.0
    - certifi==2022.9.24
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.5
    - confuse==2.0.0
    - coverage==6.5.0
    - cryptography==38.0.1
    - decorator==5.1.1
    - deprecated==1.2.13
    - devtools==0.9.0
    - executing==0.10.0
    - future==0.18.2
    - ghp-import==2.1.0
    - graphql-core==3.2.3
    - greenlet==1.1.3.post0
    - griffe==0.22.2
    - h11==0.14.0
    - idna==3.4
    - iniconfig==1.1.1
    - ipython==8.5.0
    - isort==5.13.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - mando==0.6.4
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mergedeep==1.3.4
    - mkdocs==1.4.3
    - mkdocs-autorefs==0.4.1
    - mkdocs-glightbox==0.4.0
    - mkdocs-literate-nav==0.6.2
    - mkdocs-material==8.5.6
    - mkdocs-material-extensions==1.0.3
    - mkdocstrings==0.19.0
    - mkdocstrings-python==0.7.1
    - mypy==1.5.1
    - mypy-extensions==1.0.0
    - numpy==2.2.4
    - packaging==21.3
    - pandas==2.2.3
    - parso==0.8.3
    - pathspec==0.10.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.5.2
    - pluggy==1.0.0
    - plyse==1.0.3
    - prompt-toolkit==3.0.31
    - psycopg2-binary==2.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.11.0
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pydantic==2.4.2
    - pydantic-core==2.10.1
    - pydocstyle==6.1.1
    - pyflakes==2.5.0
    - pygments==2.13.0
    - pylama==8.4.1
    - pymdown-extensions==9.6
    - pyparsing==2.4.0
    - pytest==7.1.3
    - pytest-asyncio==0.19.0
    - pytest-cov==4.0.0
    - python-dateutil==2.8.2
    - pytz==2025.2
    - pyyaml==6.0
    - pyyaml-env-tag==0.1
    - radon==5.1.0
    - redis==4.3.5
    - requests==2.28.1
    - six==1.16.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - sqlalchemy==2.0.20
    - stack-data==0.5.1
    - starlette==0.20.4
    - starlette-context==0.3.6
    - tomli==2.0.1
    - traitlets==5.4.0
    - types-pyyaml==6.0.12.2
    - types-redis==4.3.21.6
    - types-requests==2.28.11.5
    - types-urllib3==1.26.25.4
    - typing-extensions==4.7.1
    - tzdata==2025.2
    - urllib3==1.26.13
    - uvicorn==0.18.3
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - wrapt==1.14.1
prefix: /usr/local/Caskroom/miniconda/base/envs/medconb
