name: Docker Base Image

on:
  push:
    branches: [main, develop, feature/*]
    paths:
      - "backend/Dockerfile.base"
      - "backend/environment.dev.fixed.yml"
      - ".github/workflows/docker-base.yml"
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch: {}

jobs:
  base_image_dev:
    name: Base Image w/ dev dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Extract requirements.txt ğŸ“¦
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -r '.dependencies[] | select(kind == "map") | .pip | join("\n") ' backend/environment.dev.fixed.yml \
              | egrep -v '^pip($|=)' | tee backend/requirements.txt
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push Docker image ğŸ³
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kaktus42acc/medconb-backend-base
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: dev
          directory: backend/
          dockerfile: backend/Dockerfile.base

  base_image_prod:
    name: Base Image w/o dev dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Extract requirements.txt ğŸ“¦
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -r '.dependencies[] | select(kind == "map") | .pip | join("\n") ' backend/environment.prod.fixed.yml \
              | egrep -v '^pip($|=)' | tee backend/requirements.txt
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push Docker image ğŸ³
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kaktus42acc/medconb-backend-base
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: prod
          directory: backend/
          dockerfile: backend/Dockerfile.base
