name: Docs
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages on runner ğŸ“¦
        run: |
          sudo apt update
          sudo apt install git-lfs
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install Python 3.10 ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Extract requirements.txt ğŸ“¦
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -r '.dependencies[] | select(kind == "map") | .pip | join("\n") ' backend/environment.dev.fixed.yml \
              | egrep -v '^pip($|=)' | tee backend/requirements.txt
      - name: Set up runner ğŸ“¦
        run: |
          pip3 install -r backend/requirements.txt
          git fetch  # necessary for mkdocs gh-deploy
      - name: Deploy Docs ğŸ“”
        run: mkdocs gh-deploy --force --no-history
